### ISSUE TITLE
Reader length was not a multiple of the checksums

### ISSUE THREAD

**Issue by probonopd** [AppImageCrafters/appimage-update#1]
```
me@host:~$ '/home/me/Downloads/appimage-update' appimaged-436-x86_64.AppImage 
Looking for updates of:  appimaged-436-x86_64.AppImage
Downloading zsync file:  100% |███████████████| (21/21 kB, 166.515 kB/s) [0s:0s]
Reader length was not a multiple of the checksums
```

What does "Reader length was not a multiple of the checksums" mean?

It does not update the AppImage.

**Comment by azubieta** [comment]
I've been working on several areas of the project, please retest using the latest build. If the problem persists, please upload the problematic AppImage.

**Comment by probonopd** [comment]
Thanks @azubieta, the issues does persist:

```
me@host:~$ wget https://github.com/AppImageCrafters/appimage-update/releases/download/v0.1.2/appimage-update

me@host:~$ chmod +x appimage-update 

me@host:~$ cp /isodevice/Applications/appimaged-436-x86_64.AppImage .

me@host:~$ ./appimage-update appimaged-436-x86_64.AppImage 

me@host:~$ ./appimage-update --version

flag provided but not defined: -version
Usage of ./appimage-update:
  -u string
    	Custom update info string

me@host:~$ me@host:~$ ./appimaged-436-x86_64.AppImage --appimage-updateinformation

gh-releases-zsync|probonopd|go-appimage|continuous|appimaged-*-x86_64.AppImage.zsync
me@h
```

**Comment by azubieta** [comment]
@probonopd were I could get `appimaged-436-x86_64.AppImage`? 
Only the latest build is available in the Github repo

**Comment by probonopd** [comment]
[appimaged-436-x86_64.AppImage.zip](https://github.com/AppImageCrafters/appimage-update/files/4742122/appimaged-436-x86_64.AppImage.zip)

Zipped here because GitHub Issues only allows very few file types

**Comment by azubieta** [comment]
It seems that the target zsync file has some extra bytes. I patched the zsync implementation to read no more chunks than what's required.

Please re-test using https://github.com/AppImageCrafters/appimage-update/releases/tag/v0.1.3

**Comment by probonopd** [comment]
I confirm that it is working for me now. Thank you very much @azubieta 👍
